// ============================================================
// PhishGuard — Known Phishing Domains, URL Shorteners & Urgency Phrases
// ============================================================

/**
 * Known phishing / malicious domains.
 * These are common typo-squatting, look-alike, and historically malicious domains.
 */
const KNOWN_PHISHING_DOMAINS = new Set([
  "10.0.0.1",
  "192.168.1.100",
  "account-google-verify.com",
  "account-locked-alert.com",
  "adobe-license-renew.com",
  "airtel-money-verify.co.ke",
  "amaz0n-security.com",
  "amazon-order-issue.com",
  "amazon-prime-trial.tk",
  "apple-support-verify.info",
  "appleid.apple.com.verify-account.xyz",
  "auspost-parcel-notice.com",
  "aws-billing-alert.com",
  "bankofamerica-secure-login.com",
  "barclays-update.com",
  "bestbuy-deal-alert.com",
  "bitcoin-profit-guaranteed.com",
  "canada-post-delivery.com",
  "citibank-security.com",
  "click-here-to-verify.com",
  "confirm-identity-now.com",
  "confirm-order-details.com",
  "coop-bank-verify.co.ke",
  "costco-survey-reward.com",
  "credit-score-free-check.com",
  "crypto-invest-now.com",
  "device-login-alert.com",
  "dhl-parcel-update.info",
  "discord-nitro-free.com",
  "document-share-view.com",
  "dropbox-share.com",
  "ecitizen-verify.co.ke",
  "epic-games-verify.com",
  "equity-secure.net",
  "facebook-security-alert.com",
  "fedex-tracking-update.com",
  "forex-trading-signals.tk",
  "free-iphone-winner.com",
  "github-security-alert.com",
  "hmrc-tax-refund.co.uk",
  "homedepot-gift-card.info",
  "hr-policy-update.com",
  "hsbc-secure.net",
  "instagram-support.tk",
  "insurance-claim-update.com",
  "invoice-payment-portal.net",
  "irs-refund-claim.com",
  "job-offer-remote.com",
  "kcb-alert.co.ke",
  "kra-refund-portal.co.ke",
  "linkedin-verify.net",
  "login-microsoft365.tk",
  "lottery-prize-claim.net",
  "mail-upgrade-portal.com",
  "mcdonalds-survey-win.com",
  "medical-records-portal.com",
  "microsoft-outlook-verify.com",
  "mortgage-rate-update.tk",
  "mpesa-verify.co.ke",
  "my-bank-secure.com",
  "netflix-billing-update.com",
  "nhif-update.co.ke",
  "office365-password-reset.tk",
  "online-banking-verify.info",
  "password-expire-alert.com",
  "pharmacy-order-ready.com",
  "prince-inheritance.com",
  "reset-password-now.com",
  "roblox-free-robux.tk",
  "royalmail-parcel-fee.com",
  "safaricom-reward.co.ke",
  "scholarship-grant-apply.com",
  "secure-banking-login.com",
  "secure-login-portal.xyz",
  "secure.chase-online.com.login-verify.info",
  "singpost-delivery-update.com",
  "slack-workspace-verify.com",
  "snapchat-unlock.net",
  "social-security-alert.com",
  "spotify-premium-free.info",
  "starbucks-free-drink.com",
  "steamcommunity-trade.com",
  "student-loan-forgiveness.tk",
  "subscription-renewal-now.com",
  "survey-earn-money.tk",
  "target-reward-card.com",
  "tiktok-verify-account.com",
  "track-refund-status.info",
  "twitter-alert.com",
  "update-billing-info.net",
  "update-your-payment.com",
  "ups-delivery-attempt.com",
  "urgent-security-update.com",
  "usps-delivery.com",
  "verify-your-identity-now.com",
  "walmart-gift-card.com",
  "wellsfargo-alert.net",
  "whatsapp-verify.net",
  "work-from-home-earn.com",
  "www.paypal-secure-login.com",
  "zoom-meeting-invite.com",
]);

/**
 * URL shortener domains. Shortened URLs in emails are a red flag
 * because they hide the real destination.
 */
const URL_SHORTENERS = new Set([
  "bit.ly",
  "tinyurl.com",
  "goo.gl",
  "t.co",
  "ow.ly",
  "is.gd",
  "buff.ly",
  "rebrand.ly",
  "cutt.ly",
  "rb.gy",
  "shorturl.at",
  "tiny.cc",
  "bl.ink",
  "lnkd.in",
  "soo.gd",
  "s2r.co",
  "clicky.me",
  "budurl.com",
  "bc.vc",
  "v.gd",
]);

/**
 * Urgency phrases commonly found in phishing emails.
 * Each entry is a regex-ready string (case-insensitive matching).
 */
const URGENCY_PHRASES = [
  "verify your account",
  "verify your identity",
  "confirm your identity",
  "confirm your account",
  "your account will be closed",
  "your account has been suspended",
  "your account has been compromised",
  "account will be locked",
  "account will be terminated",
  "account will be deactivated",
  "unauthorized activity",
  "unauthorized login",
  "unauthorized access",
  "unusual activity",
  "unusual sign-in",
  "suspicious activity",
  "suspicious login",
  "click immediately",
  "click here immediately",
  "act now",
  "act immediately",
  "urgent action required",
  "immediate action required",
  "action required",
  "response required",
  "verify now",
  "update now",
  "update your information",
  "update your payment",
  "update your details",
  "confirm now",
  "confirm your payment",
  "within 24 hours",
  "within 48 hours",
  "your account is at risk",
  "security alert",
  "security notice",
  "security update required",
  "password expired",
  "password reset required",
  "reset your password",
  "you have won",
  "you have been selected",
  "you are a winner",
  "claim your prize",
  "claim your reward",
  "dear customer",
  "dear valued customer",
  "dear account holder",
  "we detected",
  "we noticed",
  "we have detected",
  "failure to comply",
  "failure to respond",
  "your payment was declined",
  "invoice attached",
  "overdue payment",
  "refund pending",
  "tax refund",
  "wire transfer",
  "send money",
  "lottery winner",
  "inheritance fund",
  "next of kin",
  "nigerian prince",
  "central bank of nigeria",
  "foreign remittance",
  "business proposal",
  "investment opportunity",
  "confidential transaction",
];

/**
 * Build a single RegExp from the urgency phrases list for efficient matching.
 */
const URGENCY_REGEX = new RegExp(
  URGENCY_PHRASES.map((p) => p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"),
  "gi"
);
